name: publish

on: [push]

jobs:
  publish-hso-ctf-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      run: |
        echo $CR_PAT | docker login ghcr.io -u $ACTOR --password-stdin
      env:
        CR_PAT: ${{ secrets.CR_PAT }}
        ACTOR: ${{ secrets.ACTOR }}

    - name: Build the hello-world Docker image
      run: |
        docker build . --tag ghcr.io/victorazzam/hso-ctf:latest
        #docker run ghcr.io/victorazzam/hso-ctf:latest
        docker push ghcr.io/victorazzam/hso-ctf:latest
